version: '3.8'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - gems:/usr/local/bundle:delegated
      - .:/restful-api
    ports:
      - "3000:3000"

volumes:
  gems: {}